sudo: required
service:
  - docker

before_install:
  - docker build -t heynevets/docker-react -f Dockerfile.dev .

script:
  - docker run heynevets/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-test"
  env: "DockerTest-env"
  bucket_name: "elasticbeanstalk-us-east-2-736154934556"
  bucket_path: "docker-test"
  on:
    breanch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

# resources/_runtime/_embedded_extensions/docker-test
